# -*- coding: utf-8 -*-
"""gps_solver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQAEb_xJBJEFwrSzQmmks6KuDe2zpyLz
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
c = 299792458.0

def residuals(u, satellites, pseudoranges):
  x, y, z, d = u
  F = []
  N = len(satellites)
  for i in range(N):
    xi, yi, zi = satellites[i]
    fi = ((x-xi)**2 + (y-yi)**2+(z-zi)**2) **0.5 + c*d - pseudoranges[i]
    F.append(fi)
  return np.array(F)

def R(u, satellites):
    x, y, z, d = u
    R = ((x - satellites[:,0])**2 + (y - satellites[:,1])**2 + (z - satellites[:,2])**2)**0.5
    return R

def jacobian(u, satellites, r):
  x, y, z, d = u
  N = len(satellites)
  J = np.zeros((N,4))
  J[:, 0] = (x-satellites[:,0])/r
  J[:, 1] = (y-satellites[:,1])/r
  J[:, 2] = (z-satellites[:,2])/r
  J[:, 3] = c
  return J

def solve_newton(satellites, pseudoranges, initial_guess):
  u = np.array(initial_guess, dtype=float)
  satellites = np.array(satellites, dtype=float)
  pseudoranges = np.array(pseudoranges, dtype=float)
  errors=[]

  for i in range(100):
    F = residuals(u, satellites, pseudoranges)
    r = R(u, satellites)
    J = jacobian(u, satellites, r)
    derivu = np.linalg.solve(J, -F)
    u = u+derivu
    step = np.linalg.norm(derivu)
    errors.append(step)
    if step<(10**(-8)):
      break
  return u, i+1, errors

def solve_gauss_newton(satellites, pseudoranges, initial_guess):
  u = np.array(initial_guess, dtype=float)
  satellites = np.array(satellites, dtype=float)
  pseudoranges = np.array(pseudoranges,dtype=float)
  errors = []

  for i in range(100):
    F = residuals(u, satellites, pseudoranges)
    r = R(u, satellites)
    J = jacobian(u, satellites, r)
    JTJ = J.T @ J
    JTF = J.T @ F
    derivu = np.linalg.solve(JTJ, -JTF)

    u = u+derivu
    step = np.linalg.norm(derivu)
    errors.append(step)
    if step <(10**(-8)):
      break
  return u, i+1, errors

def generate_all_plots():
  data = np.genfromtxt("Dataset.csv", delimiter=",", skip_header=1)
  satellites = data[:, 3:6]
  pseudoranges = data[:,6]
  #orange county starting guess
  initial_guess = [-2477349.6, -4698711.6, 3518811.0, 0.0]

  newton = solve_newton(satellites[:4],pseudoranges[:4], initial_guess)
  gauss_newton = solve_gauss_newton(satellites, pseudoranges, initial_guess)

  plt.figure()
  plt.semilogy(range(1, len(newton[2]) + 1), newton[2])
  plt.xlabel("Iteration")
  plt.ylabel("Update")
  plt.title("Newton's Method Convergence")
  plt.legend(["step size"])
  plt.savefig("gps_newton_error_plot.png")
  plt.close()

  plt.figure()
  plt.semilogy(range(1, len(gauss_newton[2]) + 1), gauss_newton[2])
  plt.xlabel("Iteration")
  plt.ylabel("Update")
  plt.title("Gauss-Newton Convergence")
  plt.legend(["step size"])
  plt.savefig("gps_gauss_newton_error_plot.png")
  plt.close()

